import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { phenomena, places, rules, slugId, sources, type OccurrenceView } from "@serendipity/catalog";
import { getCatalog } from "@serendipity/catalog/server";
import { ENGINE_VERSION } from "@serendipity/domain";
import { inputsHash } from "@serendipity/domain/server";

/**
 * Renders the in-repo catalog (packages/catalog) as a deterministic SQL seed that
 * `supabase db reset` / `supabase start` load, so local Supabase and CI exercise
 * the real `explore()` RPC over the same rows the web prototype ranks in memory.
 *
 *   pnpm --filter @serendipity/jobs seed:sql          # regenerate supabase/seed/catalog.sql
 *   pnpm --filter @serendipity/jobs seed:sql --check  # fail if the committed file is stale
 */

const HERE = dirname(fileURLToPath(import.meta.url));
export const SEED_PATH = resolve(HERE, "../../supabase/seed/catalog.sql");

type Sql = string;

function lit(value: string | number | boolean | null | undefined): Sql {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${value.replace(/'/g, "''")}'`;
}

function textArray(values: readonly string[]): Sql {
  return `array[${values.map(lit).join(", ")}]::text[]`;
}

function jsonb(value: unknown): Sql {
  return `${lit(JSON.stringify(value))}::jsonb`;
}

function point(lng: number, lat: number): Sql {
  return `st_setsrid(st_makepoint(${lng}, ${lat}), 4326)::geography`;
}

function range(interval: { start: string; end: string } | null): Sql {
  if (!interval) return "null";
  return `tstzrange(${lit(interval.start)}, ${lit(interval.end)}, '[)')`;
}

function seasonYearOf(row: OccurrenceView): number {
  return Number.parseInt(row.seasonKey.slice(0, 4), 10);
}

function insert(table: string, columns: readonly string[], rows: readonly Sql[][], conflict = "do nothing"): Sql {
  if (rows.length === 0) return "";
  const values = rows.map((row) => `  (${row.join(", ")})`).join(",\n");
  return `insert into ${table} (${columns.join(", ")}) values\n${values}\non conflict ${conflict};\n`;
}

export function renderSeedSql(): Sql {
  const catalog = getCatalog();
  const parts: Sql[] = [
    `-- Generated by \`pnpm --filter @serendipity/jobs seed:sql\` from packages/catalog. Do not edit.`,
    `-- engine ${ENGINE_VERSION}; ${catalog.length} occurrences across ${rules.length} rules.`,
    "begin;",
    "",
  ];

  parts.push(
    insert(
      "source",
      ["id", "url", "title", "publisher", "last_verified"],
      sources.map((s) => [lit(slugId(s.slug)), lit(s.url), lit(s.title), lit(s.publisher), lit(s.lastVerified)]),
    ),
  );

  const ordered = [...places].sort((a, b) => Number(Boolean(a.parentSlug)) - Number(Boolean(b.parentSlug)));
  parts.push(
    insert(
      "place",
      ["id", "slug", "name", "kind", "geom", "country_code", "timezone", "elevation_m", "parent_id", "description_md", "status"],
      ordered.map((p) => [
        lit(slugId(p.slug)),
        lit(p.slug),
        lit(p.name),
        lit(p.kind),
        point(p.lng, p.lat),
        lit(p.countryCode),
        lit(p.timezone),
        lit(p.elevationM ?? null),
        lit(p.parentSlug ? slugId(p.parentSlug) : null),
        lit(p.blurb),
        lit("published"),
      ]),
    ),
  );

  parts.push(
    insert(
      "phenomenon",
      ["id", "slug", "name", "family", "tags", "summary", "description_md", "practical", "spectacle", "status", "published_at"],
      phenomena.map((ph) => [
        lit(slugId(ph.slug)),
        lit(ph.slug),
        lit(ph.name),
        lit(ph.family),
        textArray(ph.tags),
        lit(ph.summary),
        lit(ph.description),
        jsonb({ ...ph.practical, howToSee: ph.howToSee, ethics: ph.ethics ?? null }),
        lit(ph.spectacle),
        lit("published"),
        "now()",
      ]),
    ),
  );

  parts.push(
    insert(
      "phenomenon_source",
      ["phenomenon_id", "source_id"],
      phenomena.flatMap((ph) => ph.sourceSlugs.map((src) => [lit(slugId(ph.slug)), lit(slugId(src))])),
    ),
  );

  parts.push(
    insert(
      "rule",
      ["id", "phenomenon_id", "place_id", "scope", "kind", "params", "confidence", "version", "active", "source_id"],
      rules.map((r) => [
        lit(slugId(r.slug)),
        lit(slugId(r.phenomenonSlug)),
        lit(r.placeSlug ? slugId(r.placeSlug) : null),
        lit(r.scope),
        lit(r.kind),
        jsonb(r.params),
        lit(r.confidence),
        "1",
        "true",
        lit(slugId(r.sourceSlug)),
      ]),
    ),
  );

  parts.push(
    insert(
      "occurrence",
      [
        "id", "rule_id", "phenomenon_id", "place_id", "scope", "season_key", "family", "tags",
        "during", "peak", "granularity", "confidence", "geom", "status", "rule_version", "engine_version",
      ],
      catalog.map((o) => [
        lit(o.id),
        lit(o.ruleId),
        lit(o.phenomenonId),
        lit(o.placeId),
        lit(o.scope),
        lit(o.seasonKey),
        lit(o.family),
        textArray(o.tags),
        range(o.during),
        range(o.peak),
        lit(o.granularity),
        lit(o.confidence),
        o.geom ? point(o.geom.coordinates[0], o.geom.coordinates[1]) : "null",
        lit(o.status),
        lit(o.ruleVersion),
        lit(o.engineVersion),
      ]),
    ),
  );

  const counts = new Map<string, number>();
  for (const o of catalog) {
    const key = `${o.ruleId}|${seasonYearOf(o)}`;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  parts.push(
    insert(
      "rule_materialization",
      ["rule_id", "season_year", "rule_version", "engine_version", "inputs_hash", "row_count"],
      [...counts.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, count]) => {
        const [ruleId, year] = key.split("|") as [string, string];
        return [lit(ruleId), year, "1", lit(ENGINE_VERSION), lit(inputsHash({ ruleId, year, count })), String(count)];
      }),
    ),
  );

  parts.push("commit;", "");
  return parts.join("\n");
}

async function main(): Promise<void> {
  const rendered = renderSeedSql();
  if (process.argv.includes("--check")) {
    const committed = await readFile(SEED_PATH, "utf8").catch(() => "");
    if (committed !== rendered) {
      console.error(`${SEED_PATH} is stale; run: pnpm --filter @serendipity/jobs seed:sql`);
      process.exit(1);
    }
    console.log(`seed up to date (${rendered.length} bytes)`);
    return;
  }
  await writeFile(SEED_PATH, rendered);
  console.log(`wrote ${SEED_PATH} (${rendered.length} bytes)`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
